### PR TITLE
Update to Django 2

### PR DESCRIPTION
**Pull request by gohanko**

### CODE REVIEW

**Comment by gabn88** [comment]
When does this get merged in?

**Comment by gohanko** [comment]
I don't think its his priority now. I did wrote a small app separate from this that uses tinymce 4 but I removed it since I wasn't using it and no one was using it either.
Basically the app just use applies the tinymce js to the admin dashboard. It was around 3 lines of code with a dependency called django-tinymce-lite

**Comment by gohanko** [comment]
That thing is much more simpler than this.

**Comment by gabn88** [comment]
Ok, I'm now starting a new blog with Django. Do you recommend something else then Django zinnia? It is quite a lot of work to setup and I don't like the template overloading.

**Comment by gohanko** [comment]
In all honesty, if you are just starting a blog, you should use something like GitHub pages, you'll avoid all the headache of coding and deploying the webapp, if you need custom functionalities, then this should be fine. One thing with django is that it is quite bloated, even the functionalities that comes with the apps like zinnia is very bloated. I also really dislike the template overloading, its a pain to figure out how it works and build it accordingly. Honestly, if I were to build a blog using python now, I would just code it with something like flask, at least you know the components of your site and at least it isn't bloated like django is and you have full control except for the low level stuff that flask handles.

**Comment by gabn88** [comment]
Ok, thanks. I have already a huge django webapp and thought it would be easy to add a blog to it. Will think about the options, as I don't like re-inventing the wheel.

**Comment by gohanko** [comment]
Imo django is more suitable to big production sites rather than small websites. If you are building a blogging service to sell, django is perfect but for a small site, I think its just an overkill.  Big sites always use most of the functionalities django provides and apps like zinnia provides but smaller sites almost never use them or doesn't care about it.

**Comment by gohanko** [comment]
@gabn88 adding django zinnia is easy. I could help you figure out how to add tinymce4 to your site, this one uses the old 3.5 which lacks features such as code highlighting. I should have kept the django app I wrote up on pypi at least. The template overload is very "messy" but is doable. It takes a lot of set up time but shouldn't take more than a day, I got my blog up in 1 day before.

**Comment by gabn88** [comment]
Ok, thank you. I got django-zinnia working, but after adding zinnia-theme-bootstrap things started to break down. 
I'm quite sure django-app-namespace-template-loader is the culprit, but that is also needed for zinnia-threaded-comments. 

So I'm now thinking to stop using comments for now, most blog posts will be added to our facebook page anyway, and there is place enough for comments. Or maybe just create our own threated comments template to start with.

**Comment by gohanko** [comment]
You could disable the comments and use something like discuss for it. By the way, zinnia-theme-bootstrap is just template overrides, so it's best to just copy what you need from the zinnia source and paste and modify it as you need, just so you have the latest version rather than one from a few years ago.

**Comment by gabn88** [comment]
To be honoust, I think I will just include 1 default template and not use {{ object.content_template }} at all. That makes things so hard to understand. However, I guess we're still stuck with the fact that on the home page and the detail page the same template has to be used, which is already a bogger :(

**Comment by gohanko** [comment]
Not really, you can use a separate template for the list and a separate template for the details page. I forgot what it is though, so you probably need to spend some time experimenting.

**Comment by gohanko** [comment]
It was something around  	_entry_detail.html,  	_entry_detail_base.html, entry_detail.html, entry_detail_base.html or entry_archive or entry_list.html

**Comment by gabn88** [comment]
I think I found it: https://github.com/Fantomas42/django-blog-zinnia/issues/383 Hmm, I thought this was going to be easy  ;) I just wanted a blog with search, list view and detail view. :grinning:

**Comment by gohanko** [comment]
Oh man, I didn't find that the first time, had to spend a few hours experimenting.

**Pull request closed without merging**
